import { NextResponse } from 'next/server'
import { db } from '@/lib/db'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/app/api/auth/[...nextauth]/route'
import { getWeakThemesWithRecommendations } from '@/lib/groq'

export async function GET() {
  try {
    const session = await getServerSession(authOptions)
    if (!session?.user?.email) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    const user = await db.user.findUnique({ where: { email: session.user.email } })
    if (!user) return NextResponse.json({ error: 'User not found' }, { status: 404 })

    // Check cache: report generated by self (teacherId === studentId) today
    const todayStart = new Date()
    todayStart.setUTCHours(0, 0, 0, 0)

    const cached = await db.studentWeakThemesReport.findFirst({
      where: {
        studentId: user.id,
        teacherId: user.id,
        generatedAt: { gte: todayStart }
      },
      orderBy: { generatedAt: 'desc' }
    })

    if (cached) {
      return NextResponse.json({ report: cached })
    }

    // Build themes from missed puzzles
    const missed = await db.missedPuzzle.findMany({ where: { userId: user.id } })
    if (missed.length === 0) {
      return NextResponse.json({ error: 'Недостаточно данных. Решите несколько задач, чтобы получить рекомендации.' }, { status: 400 })
    }

    const themesCount: Record<string, number> = {}
    for (const m of missed) {
      if (!m.themes) continue
      for (const t of m.themes.split(' ')) {
        if (t) themesCount[t] = (themesCount[t] || 0) + 1
      }
    }

    if (Object.keys(themesCount).length === 0) {
      return NextResponse.json({ error: 'Нет данных по темам.' }, { status: 400 })
    }

    // Top weak themes for filtering
    const topWeakThemes = Object.entries(themesCount)
      .sort((a, b) => b[1] - a[1])
      .slice(0, 8)
      .map(([t]) => t)

    // Pre-filter videos and openings by tag intersection
    const allVideos = await db.video.findMany({ select: { id: true, title: true, tags: true } })
    const allOpenings = await db.opening.findMany({ select: { id: true, title: true, tags: true } })

    const matchedVideos = allVideos.filter(v => {
      if (!v.tags) return false
      return v.tags.split(' ').some(tag => topWeakThemes.includes(tag))
    }).map(v => ({ id: v.id, title: v.title }))

    const matchedOpenings = allOpenings.filter(o => {
      if (!o.tags) return false
      return o.tags.split(' ').some(tag => topWeakThemes.includes(tag))
    }).map(o => ({ id: o.id, title: o.title }))

    const result = await getWeakThemesWithRecommendations(
      themesCount,
      user.name || 'Игрок',
      matchedVideos,
      matchedOpenings
    )

    const report = await db.studentWeakThemesReport.create({
      data: {
        studentId: user.id,
        teacherId: user.id, // self-service marker
        themesJson: JSON.stringify(themesCount),
        recommendation: result.recommendation,
        recommendationsJson: JSON.stringify({
          recommendedVideos: result.recommendedVideos,
          recommendedOpenings: result.recommendedOpenings
        })
      }
    })

    return NextResponse.json({ report })
  } catch (error) {
    console.error('GET /api/my/weak-themes error:', error)
    return NextResponse.json({ error: 'Internal Server Error' }, { status: 500 })
  }
}
