export const MAX_SELECTED_THEMES = 3;

export const PUZZLE_THEMES: { code: string; ru: string }[] = [
  { code: "mate", ru: "Мат" },
  { code: "mateIn1", ru: "Мат в 1 ход" },
  { code: "mateIn2", ru: "Мат в 2 хода" },
  { code: "mateIn3", ru: "Мат в 3 хода" },
  { code: "mateIn4", ru: "Мат в 4 хода" },
  { code: "mateIn5", ru: "Мат в 5 ходов" },
  { code: "backRankMate", ru: "Мат на последней линии" },
  { code: "smotheredMate", ru: "Спёртый мат" },
  { code: "doubleBishopMate", ru: "Мат двумя слонами" },
  { code: "bodenMate", ru: "Мат Бодена" },
  { code: "anastasiaMate", ru: "Мат Анастасии" },
  { code: "arabianMate", ru: "Арабский мат" },
  { code: "hookMate", ru: "Мат крюком" },
  { code: "dovetailMate", ru: "Мат «ласточкин хвост»" },
  { code: "vukovicMate", ru: "Мат Вуковича" },
  { code: "ladderMate", ru: "Лестничный мат" },
  { code: "killBoxMate", ru: "Мат «коробкой»" },
  { code: "fork", ru: "Вилка" },
  { code: "pin", ru: "Связка" },
  { code: "skewer", ru: "Протыкание" },
  { code: "discoveredAttack", ru: "Открытое нападение" },
  { code: "doubleCheck", ru: "Двойной шах" },
  { code: "sacrifice", ru: "Жертва" },
  { code: "deflection", ru: "Отвлечение" },
  { code: "attraction", ru: "Приманка" },
  { code: "clearance", ru: "Освобождение поля" },
  { code: "interference", ru: "Перекрытие" },
  { code: "intermezzo", ru: "Промежуточный ход" },
  { code: "quietMove", ru: "Тихий ход" },
  { code: "xRayAttack", ru: "Рентген-атака" },
  { code: "zugzwang", ru: "Цугцванг" },
  { code: "capturingDefender", ru: "Устранение защитника" },
  { code: "exposedKing", ru: "Раскрытый король" },
  { code: "hangingPiece", ru: "Висящая фигура" },
  { code: "trappedPiece", ru: "Запертая фигура" },
  { code: "advancedPawn", ru: "Продвинутая пешка" },
  { code: "kingsideAttack", ru: "Атака на короля" },
  { code: "queensideAttack", ru: "Атака на ферзевом фланге" },
  { code: "defensiveMove", ru: "Защитный ход" },
  { code: "promotion", ru: "Превращение пешки" },
  { code: "underPromotion", ru: "Слабое превращение" },
  { code: "enPassant", ru: "Взятие на проходе" },
  { code: "castling", ru: "Рокировка" },
  { code: "opening", ru: "Дебют" },
  { code: "middlegame", ru: "Миттельшпиль" },
  { code: "endgame", ru: "Эндшпиль" },
  { code: "rookEndgame", ru: "Ладейный эндшпиль" },
  { code: "bishopEndgame", ru: "Слоновый эндшпиль" },
  { code: "knightEndgame", ru: "Коневой эндшпиль" },
  { code: "pawnEndgame", ru: "Пешечный эндшпиль" },
  { code: "queenEndgame", ru: "Дамский эндшпиль" },
  { code: "queenRookEndgame", ru: "Дамско-ладейный эндшпиль" },
  { code: "advantage", ru: "Преимущество" },
  { code: "crushing", ru: "Решающее преимущество" },
  { code: "equality", ru: "Уравнение позиции" },
  { code: "master", ru: "Партия мастеров" },
  { code: "masterVsMaster", ru: "Мастер против мастера" },
  { code: "superGM", ru: "Партия супергроссмейстеров" },
  { code: "short", ru: "Короткая задача" },
  { code: "long", ru: "Длинная задача" },
  { code: "veryLong", ru: "Очень длинная задача" },
  { code: "oneMove", ru: "В один ход" },
  { code: "attackingF2F7", ru: "Атака на f2/f7" },
];
